openapi: 3.0.0
info:
  title: ClimeCheck Data API
  description: Manage feeds data, data collection and analysis
  version: 1.0

servers:
  - url: http://localhost:16280/sensor-data/api/v1
  - description: Climecheck data API documentation
  
paths:
  /docs:
    get:
      tags:
        - Doc
      responses: 
        '200':
          description: success
  /feeds/create:
    post:
      tags:
        - Add New Feed
      paramters:
      - in: "body"
        schema:
          $ref: "#/definitions/feeds"
        responses:
          "200":
            description: "Success"
